@startuml
actor User
activate Flashcard
User -> CommandInsertCode : executeCommand()
activate CommandInsertCode
CommandInsertCode -> Ui : showToUser()
activate Ui
return
CommandInsertCode -> Flashcard : insertCodeSnippet(int, String)
deactivate CommandInsertCode
@enduml